version: '3'
services:
  minio:
    image: ${MS_IMAGE_PREFIX}/minio:RELEASE.2024-01-31T20-20-33Z
    container_name: minio
    hostname: "minio"
    deploy:
      resources:
        limits:
          memory: ${MS_MINIO_MEM_LIMIT:-1g}
    ports:
      - '9000:9000'
      - '9001:9001'
    healthcheck:
      test: [ "CMD", "bash", "-c", "< /dev/tcp/localhost/9000" ]
      interval: 6s
      timeout: 10s
      retries: 50
    environment:
      MINIO_ACCESS_KEY: ${MS_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MS_MINIO_SECRET_KEY}
    volumes:
      - ms-minio-data:/data
    networks:
      - ms-network
    command: server --console-address ':9001' /data
    privileged: true
    restart: always

volumes:
  ms-minio-data:
    driver_opts:
      type: none
      device: ${MS_BASE}/metersphere/data/minio
      o: bind