version: "3"
services:
  chrome:
    image: ${MS_IMAGE_PREFIX}/node-chromium:4.10.0
    container_name: selenium-chrome
    shm_size: 2gb
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    entrypoint: bash -c '[ ! -f /home/seluser/language ] && sudo sed -i -e "s/# $$LANG.*/$$LANG UTF-8/" /etc/locale.gen && sudo dpkg-reconfigure --frontend=noninteractive locales && sudo update-locale LANG=$$LANG && touch /home/seluser/language; /opt/bin/entry_point.sh'
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - TZ=Asia/Shanghai
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - JAVA_OPTS=-Xmx400m -Dfile.encoding=utf-8
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - LANGUAGE=zh_CN.UTF-8
      - LANG=zh_CN.UTF-8
      - SE_START_VNC=false
      - SE_VNC_VIEW_ONLY=1
      - SE_VNC_PASSWORD=Password123@selenium
    restart: always
    healthcheck:
      test: ["CMD", "bash", "-c", "< /dev/tcp/localhost/5900"]
      interval: 6s
      timeout: 5s
      retries: 50
    networks:
      - ms-network
  firefox:
    image: ${MS_IMAGE_PREFIX}/node-firefox:4.10.0
    container_name: selenium-firefox
    shm_size: 2gb
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    entrypoint: bash -c '[ ! -f /home/seluser/language ] && sudo sed -i -e "s/# $$LANG.*/$$LANG UTF-8/" /etc/locale.gen && sudo dpkg-reconfigure --frontend=noninteractive locales && sudo update-locale LANG=$$LANG && touch /home/seluser/language; /opt/bin/entry_point.sh'
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - TZ=Asia/Shanghai
      - SE_NODE_MAX_SESSIONS=6
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - JAVA_OPTS=-Xmx400m -Dfile.encoding=utf-8
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - LANGUAGE=zh_CN.UTF-8
      - LANG=zh_CN.UTF-8
      - SE_START_VNC=false
      - SE_VNC_VIEW_ONLY=1
      - SE_VNC_PASSWORD=Password123@selenium
    restart: always
    healthcheck:
      test: [ "CMD", "bash", "-c", "< /dev/tcp/localhost/5900" ]
      interval: 6s
      timeout: 5s
      retries: 50
    networks:
      - ms-network

  selenium-hub:
    image: ${MS_IMAGE_PREFIX}/selenium-hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444" ]
      interval: 6s
      timeout: 5s
      retries: 50
    networks:
      - ms-network