version: "2.1"
services:
  zookeeper:
    image: '${MS_IMAGE_PREFIX}/zookeeper:3'
    container_name: zookeeper
    healthcheck:
      test: ["CMD", "zkServer.sh", "version"]
      interval: 6s
      timeout: 10s
      retries: 20
    volumes:
      - 'ms-zookeeper-data:/bitnami'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    restart: always
    networks:
      - ms-network
  kafka:
    image: '${MS_IMAGE_PREFIX}/kafka:2'
    container_name: kafka
    ports:
      - '${MS_KAFKA_PORT}:${MS_KAFKA_PORT}'
    healthcheck:
      test: ["CMD", "kafka-consumer-groups.sh", "--bootstrap-server", "localhost:9093", "--list"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - 'ms-kafka-data:/bitnami'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9093,EXTERNAL://:${MS_KAFKA_PORT}
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      KAFKA_CFG_LOG_RETENTION_HOURS: 64
      KAFKA_CFG_MAX_REQUEST_SIZE: 52428800
      KAFKA_CFG_MESSAGE_MAX_BYTES: 52428800
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 52428800
      KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES: 52428800
      KAFKA_CFG_PARTITION_FETCH_BYTES: 52428800
      FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS: 'true'
    depends_on:
      - zookeeper
    networks:
      - ms-network
  ms-data-streaming:
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  ms-zookeeper-data:
    driver_opts:
      type: none
      device: ${MS_BASE}/metersphere/data/zookeeper
      o: bind
  ms-kafka-data:
    driver_opts:
      type: none
      device: ${MS_BASE}/metersphere/data/kafka
      o: bind
