version: "3"
services:
  kafka:
    image: '${MS_IMAGE_PREFIX}/kafka:3.7.0-rc2'
    container_name: kafka
    ports:
      - '${MS_KAFKA_PORT}:9092'
    healthcheck:
      test: [ "CMD", "bash", "-c", "< /dev/tcp/localhost/9092" ]
      interval: 6s
      timeout: 10s
      retries: 50
    restart: always
    volumes:
      - ${MS_BASE}/metersphere/conf/kafka/config:/mnt/shared/config
    environment:
      # Environment variables used by kafka scripts will be needed in case of File input.
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      # Set properties not provided in the file input
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      # Override an existing property
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://${MS_KAFKA_HOST}:${MS_KAFKA_PORT},PLAINTEXT://kafka:19092'

    networks:
      - ms-network
  result-hub:
    depends_on:
      kafka:
        condition: service_healthy

