version: "3"
services:
  result-hub:
    image: ${MS_IMAGE_PREFIX}/metersphere-ce:${MS_IMAGE_TAG}
    container_name: result-hub
    deploy:
      resources:
        limits:
          memory: ${MS_RESULT_MEM_LIMIT}
    entrypoint: 
      - sh
      - -c
      - |
        sh /shells/result-hub.sh
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      REDIS_HOST: ${MS_REDIS_HOST}
      REDIS_PORT: ${MS_REDIS_PORT}
      REDIS_PASSWORD: ${MS_REDIS_PASSWORD}
      MINIO_ENDPOINT: ${MS_MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MS_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MS_MINIO_SECRET_KEY}
    healthcheck:
      test: [ "CMD", "bash", "-c", "< /dev/tcp/localhost/8084" ]
      interval: 6s
      timeout: 10s
      retries: 50
    restart: always
    volumes:
      - ${MS_BASE}/metersphere/conf/metersphere.properties:/opt/metersphere/conf/metersphere.properties
      - ${MS_BASE}/metersphere/conf/redisson.yml:/opt/metersphere/conf/redisson.yml
      - ${MS_BASE}/metersphere/logs/result-hub:/opt/metersphere/logs/result-hub
    networks:
      - ms-network
