version: "3"
services:
  metersphere:
    image: ${MS_IMAGE_PREFIX}/metersphere-ce:${MS_IMAGE_TAG}
    container_name: metersphere
    deploy:
      resources:
        limits:
          memory: ${MS_MEM_LIMIT}
    entrypoint: 
      - sh
      - -c
      - |
        sh /shells/metersphere.sh
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MS_MYSQL_HOST}:${MS_MYSQL_PORT}/${MS_MYSQL_DB}?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&sessionVariables=sql_mode=%27STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION%27
      SPRING_DATASOURCE_USERNAME: ${MS_MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MS_MYSQL_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${MS_KAFKA_HOST}:${MS_KAFKA_PORT}
      K8S_TASK_RUNNER_IMAGE: ${MS_IMAGE_PREFIX}/task-runner:${MS_IMAGE_TAG}
      SPRING_SESSION_TIMEOUT: '30d'
      REDIS_HOST: ${MS_REDIS_HOST}
      REDIS_PORT: ${MS_REDIS_PORT}
      REDIS_PASSWORD: ${MS_REDIS_PASSWORD}
      MINIO_ENDPOINT: ${MS_MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MS_MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MS_MINIO_SECRET_KEY}
      TOTP_SECRET: ${MS_TOTP_SECRET}
    ports:
      - ${MS_SERVER_PORT}:8081
    healthcheck:
      test: [ "CMD", "bash", "-c", "< /dev/tcp/localhost/8081" ]
      interval: 6s
      timeout: 10s
      retries: 50
    restart: always
    volumes:
      - ${MS_BASE}/metersphere/conf:/opt/metersphere/conf
      - ${MS_BASE}/metersphere/logs/metersphere:/opt/metersphere/logs/metersphere
    networks:
      - ms-network
